import { CapapieProduct, DisplayProduct } from '@/types/product-data';

// Auto-generated from capapiesports.com by scripts/scrape-capapie.js
// DO NOT EDIT MANUALLY - run `node scripts/scrape-capapie.js` to regenerate.

export const capapieProductsData: CapapieProduct[] = [
  {
    product_code: "1028",
    slug: "rifle-stand",
    product_name: "RIFLE STAND",
    category: "Accessories",
    short_description: "The rifle stand is made of aircraft-grade aluminium which automatically makes it lightweight, durable, and sturdy. A well-researched and engineered method is used for the design. We have stressed maintaining the balance and weight-bearing c",
    long_description: "The rifle stand is made of aircraft-grade aluminium which automatically makes it lightweight, durable, and sturdy. A well-researched and engineered method is used for the design. We have stressed maintaining the balance and weight-bearing capacity of the stand. Its compact structure makes it easily portable. These stands come with a pellet box holder attachment and can extend to any desirable height.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "rifle-stand_1.jpg",
    images: ["rifle-stand_1.jpg"],
    product_link: "https://capapiesports.com/product_details/rifle-stand/QO9S8IV1N3",
  },
  {
    product_code: "1030",
    slug: "capapie-shooting-cap",
    product_name: "CAPAPIE SHOOTING CAP",
    category: "Accessories",
    short_description: "The shooting cap is designed in accordance with ISSF, from soft lightweight weight stretchable Neoprene Fabric. A Velcro strap is given for individual adjustment and helps the shooter avoid the distraction of unwanted light.",
    long_description: "The shooting cap is designed in accordance with ISSF, from soft lightweight weight stretchable Neoprene Fabric. A Velcro strap is given for individual adjustment and helps the shooter avoid the distraction of unwanted light.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-shooting-cap_1.jpg",
    images: ["capapie-shooting-cap_1.jpg","capapie-shooting-cap_2.jpg","capapie-shooting-cap_3.jpg"],
    product_link: "https://capapiesports.com/product_details/capapie-shooting-cap/SSAZ0WEUT2",
  },
  {
    product_code: "1035",
    slug: "soft-rifle-case",
    product_name: "SOFT RIFLE CASE",
    category: "Accessories",
    short_description: "Soft Rifle Case",
    long_description: "Soft Rifle Case",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "soft-rifle-case_1.png",
    images: ["soft-rifle-case_1.png","soft-rifle-case_2.png"],
    product_link: "https://capapiesports.com/product_details/soft-rifle-case/LWS5KIGGMW",
  },
  {
    product_code: "1040",
    slug: "non-stretchable-rifle-sling",
    product_name: "NON-STRETCHABLE RIFLE SLING",
    category: "Accessories",
    short_description: "Sling made of non-stretchable material with cutout for hook attachment to Jacket, for better positioning. Anti-slip rubber is used around the arm. Two buckles are given to adjust the length and girth around the arm. It complies with ISSF ru",
    long_description: "Sling made of non-stretchable material with cutout for hook attachment to Jacket, for better positioning. Anti-slip rubber is used around the arm. Two buckles are given to adjust the length and girth around the arm. It complies with ISSF rule number 7.5.8.2",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "non-stretchable-rifle-sling_1.jpg",
    images: ["non-stretchable-rifle-sling_1.jpg","non-stretchable-rifle-sling_2.jpg","non-stretchable-rifle-sling_3.jpg"],
    product_link: "https://capapiesports.com/product_details/non-stretchable-rifle-sling/IAZ5NHSO3B",
  },
  {
    product_code: "1041",
    slug: "pro-tin-holder",
    product_name: "PRO TIN HOLDER",
    category: "Accessories",
    short_description: "Pro Tin Holder",
    long_description: "Pro Tin Holder",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "pro-tin-holder_1.png",
    images: ["pro-tin-holder_1.png"],
    product_link: "https://capapiesports.com/product_details/pro-tin-holder/JG3C460EZI",
  },
  {
    product_code: "1043",
    slug: "canvas-kneeling-roll",
    product_name: "CANVAS KNEELING ROLL",
    category: "Accessories",
    short_description: "Canvas Kneeling Roll",
    long_description: "Canvas Kneeling Roll",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "canvas-kneeling-roll_1.png",
    images: ["canvas-kneeling-roll_1.png","canvas-kneeling-roll_2.png","canvas-kneeling-roll_3.png","canvas-kneeling-roll_4.png"],
    product_link: "https://capapiesports.com/product_details/canvas-kneeling-roll/DR1OYSANSN",
  },
  {
    product_code: "1044",
    slug: "pro-shooting-mat",
    product_name: "PRO SHOOTING MAT",
    category: "Accessories",
    short_description: "It is made of 100% nylon waterproof material. Black-color rectangle-shaped anti-slip rubber is placed below the elbow positioning area. Inside the shooting mat, high-density polyethylene padding is used for comfortable positioning. It is sp",
    long_description: "It is made of 100% nylon waterproof material. Black-color rectangle-shaped anti-slip rubber is placed below the elbow positioning area. Inside the shooting mat, high-density polyethylene padding is used for comfortable positioning. It is specially designed to fold into a portable size and has attached handles to easily carry anywhere. Used only in the prone position.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "pro-shooting-mat_1.jpg",
    images: ["pro-shooting-mat_1.jpg","pro-shooting-mat_2.jpg","pro-shooting-mat_3.jpg"],
    product_link: "https://capapiesports.com/product_details/pro-shooting-mat/CV1ERJIA9A",
  },
  {
    product_code: "1048",
    slug: "pro-match-box",
    product_name: "PRO MATCH BOX",
    category: "Accessories",
    short_description: "Pro Match Box",
    long_description: "Pro Match Box",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "pro-match-box_1.png",
    images: ["pro-match-box_1.png","pro-match-box_2.png","pro-match-box_3.png"],
    product_link: "https://capapiesports.com/product_details/pro-match-box/EBAM6XGQ4O",
  },
  {
    product_code: "1055",
    slug: "metal-buttons",
    product_name: "METAL BUTTONS",
    category: "Accessories",
    short_description: "The metal buttons have a nickel finish for an attractive look and feel. They are designed with unique screw buttons on the Jacket according to the shooter’s requirement.",
    long_description: "The metal buttons have a nickel finish for an attractive look and feel. They are designed with unique screw buttons on the Jacket according to the shooter’s requirement.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "metal-buttons_1.jpg",
    images: ["metal-buttons_1.jpg","metal-buttons_2.jpg","metal-buttons_3.jpg"],
    product_link: "https://capapiesports.com/product_details/metal-buttons/XTHWIVLQCT",
  },
  {
    product_code: "1057",
    slug: "kneeling-pad",
    product_name: "KNEELING PAD",
    category: "Accessories",
    short_description: "Kneeling Pad",
    long_description: "Kneeling Pad",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "kneeling-pad_1.png",
    images: ["kneeling-pad_1.png"],
    product_link: "https://capapiesports.com/product_details/kneeling-pad/R9GYU670K4",
  },
  {
    product_code: "1058",
    slug: "safety-flag-rifle",
    product_name: "SAFETY FLAG RIFLE",
    category: "Accessories",
    short_description: "Safety Flag Rifle",
    long_description: "Safety Flag Rifle",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "safety-flag-rifle_1.png",
    images: ["safety-flag-rifle_1.png","safety-flag-rifle_2.png"],
    product_link: "https://capapiesports.com/product_details/safety-flag-rifle/2CNERZFMA0",
  },
  {
    product_code: "1058",
    slug: "safety-flag-pistol",
    product_name: "SAFETY FLAG PISTOL",
    category: "Accessories",
    short_description: "Safety Flag Pistol",
    long_description: "Safety Flag Pistol",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "safety-flag-pistol_1.png",
    images: ["safety-flag-pistol_1.png","safety-flag-pistol_2.png"],
    product_link: "https://capapiesports.com/product_details/safety-flag-pistol/ZEOFCFRKH9",
  },
  {
    product_code: "1059",
    slug: "premium-shooting-belt",
    product_name: "PREMIUM SHOOTING BELT",
    category: "Accessories",
    short_description: "The belt is made of non-stretchable high-quality material and comes in all sizes with a dual loop design for enhanced strength. It is made according to ISSF rule number 7.5.5.1. Standards. Available in black color only.",
    long_description: "The belt is made of non-stretchable high-quality material and comes in all sizes with a dual loop design for enhanced strength. It is made according to ISSF rule number 7.5.5.1. Standards. Available in black color only.",
    features: [],
    colors: [],
    sizing: "The belt is made of non-stretchable high-quality material and comes in all sizes with a dual loop design for enhanced strength. It is made according to ISSF rule number 7.5.5.1. Standards. Available in black color only.",
    image_filename: "premium-shooting-belt_1.jpg",
    images: ["premium-shooting-belt_1.jpg","premium-shooting-belt_2.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-shooting-belt/T8QWXHGSST",
  },
  {
    product_code: "1070",
    slug: "canvas-kneeling-roll-with-anti-slip-rubber",
    product_name: "CANVAS KNEELING ROLL WITH ANTI SLIP RUBBER",
    category: "Accessories",
    short_description: "It is made of canvas material and is filled with cork granules for comfortable positioning. The canvas Kneeling Roll is placed under the top of the ankle above the foot, which gives great support and avoids imbalanced movements. Anti-slip r",
    long_description: "It is made of canvas material and is filled with cork granules for comfortable positioning. The canvas Kneeling Roll is placed under the top of the ankle above the foot, which gives great support and avoids imbalanced movements. Anti-slip rubber padding further reduces any accidental slips and increases friction.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "canvas-kneeling-roll-with-anti-slip-rubber_1.png",
    images: ["canvas-kneeling-roll-with-anti-slip-rubber_1.png","canvas-kneeling-roll-with-anti-slip-rubber_2.png","canvas-kneeling-roll-with-anti-slip-rubber_3.png"],
    product_link: "https://capapiesports.com/product_details/canvas-kneeling-roll-with-anti-slip-rubber/SB8FHOZ5NE",
  },
  {
    product_code: "1074",
    slug: "premium-shooting-mat",
    product_name: "PREMIUM SHOOTING MAT",
    category: "Accessories",
    short_description: "It is made of 100% nylon waterproof material. Rectangle-shaped TOP GRIP is placed below the elbow positioning area. Inside the shooting mat, high-density polyethylene foam is used for comfortable positioning. A zipper is provided for the fo",
    long_description: "It is made of 100% nylon waterproof material. Rectangle-shaped TOP GRIP is placed below the elbow positioning area. Inside the shooting mat, high-density polyethylene foam is used for comfortable positioning. A zipper is provided for the foam pad’s adjustment. It is specially designed to fold into portable size and handles are attached to carry easily anywhere. Velcro straps retain all four parts in a compact package.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "premium-shooting-mat_1.jpg",
    images: ["premium-shooting-mat_1.jpg","premium-shooting-mat_2.jpg","premium-shooting-mat_3.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-shooting-mat/KDFJYSNFH7",
  },
  {
    product_code: "1080",
    slug: "shoe-lace",
    product_name: "SHOE LACE",
    category: "Accessories",
    short_description: "Shoe Lace",
    long_description: "Shoe Lace",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "shoe-lace_1.png",
    images: ["shoe-lace_1.png","shoe-lace_2.png"],
    product_link: "https://capapiesports.com/product_details/shoe-lace/VCTAPC0EEW",
  },
  {
    product_code: "1081",
    slug: "shoes-insole",
    product_name: "SHOES INSOLE",
    category: "Accessories",
    short_description: "Shoes Insole",
    long_description: "Shoes Insole",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "shoes-insole_1.png",
    images: ["shoes-insole_1.png"],
    product_link: "https://capapiesports.com/product_details/shoes-insole/OQSUSRIPCK",
  },
  {
    product_code: "1082",
    slug: "cork",
    product_name: "CORK",
    category: "Accessories",
    short_description: "Cork",
    long_description: "Cork",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "cork_1.png",
    images: ["cork_1.png","cork_2.png"],
    product_link: "https://capapiesports.com/product_details/cork/1KAAB6CLWM",
  },
  {
    product_code: "1086",
    slug: "premium-carbon-stand",
    product_name: "PREMIUM CARBON STAND",
    category: "Accessories",
    short_description: "Premium Carbon Stand",
    long_description: "Premium Carbon Stand",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "premium-carbon-stand_1.png",
    images: ["premium-carbon-stand_1.png","premium-carbon-stand_2.png","premium-carbon-stand_3.png"],
    product_link: "https://capapiesports.com/product_details/premium-carbon-stand/ILAPSFAV0W",
  },
  {
    product_code: "1087",
    slug: "pro-headband",
    product_name: "PRO HEADBAND",
    category: "Accessories",
    short_description: "Pro HeadBand",
    long_description: "Pro HeadBand",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "pro-headband_1.png",
    images: ["pro-headband_1.png","pro-headband_2.png"],
    product_link: "https://capapiesports.com/product_details/pro-headband/CHCNYFTUUL",
  },
  {
    product_code: "1091",
    slug: "polo-tshirt",
    product_name: "POLO TSHIRT",
    category: "Accessories",
    short_description: "Polo Tshirt",
    long_description: "Polo Tshirt",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "polo-tshirt_1.png",
    images: ["polo-tshirt_1.png","polo-tshirt_2.png","polo-tshirt_3.png","polo-tshirt_4.png"],
    product_link: "https://capapiesports.com/product_details/polo-tshirt/X4DTY8WA1A",
  },
  {
    product_code: "1095",
    slug: "capapie-socks",
    product_name: "CAPAPIE SOCKS",
    category: "Accessories",
    short_description: "Capapie Socks",
    long_description: "Capapie Socks\n\nIntroducing the Capapie Bamboo Compression Socks – the ultimate choice for shooters. Crafted from premium bamboo fibers, these socks provide optimum compression to enhance blood circulation, ensuring peak performance. The bamboo material is naturally odor-free and skin-friendly, offering unparalleled comfort. Super soft and highly absorbent, these socks keep your feet dry and fresh throughout your shooting sessions. With Capapie Bamboo Compression Socks, experience the perfect blend of functionality and comfort, designed to meet the specific needs of shooters. Elevate your performance with socks that care for your feet and enhance your shooting experience.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-socks_1.png",
    images: ["capapie-socks_1.png","capapie-socks_2.png"],
    product_link: "https://capapiesports.com/product_details/capapie-socks/KDA2YCUG6Y",
  },
  {
    product_code: "1101",
    slug: "premium-shooting-cap-109",
    product_name: "PREMIUM SHOOTING CAP 10.9",
    category: "Accessories",
    short_description: "Premium Shooting Cap 10.9",
    long_description: "Premium Shooting Cap 10.9\n\nIntroducing the Capapie Sports Neoprene Cap – designed for ultimate performance and comfort. Made from premium neoprene, this cap ensures a snug, stretchable fit. The terry fabric top circumference absorbs sweat, keeping you dry and focused. The Capapie branding on the center front adds a touch of style. Key features include its lightweight design, adjustable Velcro strap for a personalized fit, and effective light-blocking to minimize distractions. Adhering to ISSF standards, this cap is perfect for shooters seeking both functionality and comfort. Experience unparalleled ease with the Capapie Neoprene Cap – where every detail is crafted for excellence",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "premium-shooting-cap-109_1.png",
    images: ["premium-shooting-cap-109_1.png","premium-shooting-cap-109_2.png","premium-shooting-cap-109_3.png","premium-shooting-cap-109_4.png"],
    product_link: "https://capapiesports.com/product_details/premium-shooting-cap-109/B2GT0PVVON",
  },
  {
    product_code: "1104",
    slug: "lepal-pin-capapie-logo",
    product_name: "LEPAL PIN CAPAPIE LOGO",
    category: "Accessories",
    short_description: "Lepal Pin Capapie Logo",
    long_description: "Lepal Pin Capapie Logo",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "lepal-pin-capapie-logo_1.png",
    images: ["lepal-pin-capapie-logo_1.png","lepal-pin-capapie-logo_2.png"],
    product_link: "https://capapiesports.com/product_details/lepal-pin-capapie-logo/JE9HFUH8GQ",
  },
  {
    product_code: "1105",
    slug: "lepal-pin-flag-capapie-and-india",
    product_name: "LEPAL PIN FLAG CAPAPIE AND INDIA",
    category: "Accessories",
    short_description: "Lepal Pin Flag Capapie and India",
    long_description: "Lepal Pin Flag Capapie and India",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "lepal-pin-flag-capapie-and-india_1.png",
    images: ["lepal-pin-flag-capapie-and-india_1.png","lepal-pin-flag-capapie-and-india_2.png"],
    product_link: "https://capapiesports.com/product_details/lepal-pin-flag-capapie-and-india/JDVSKPLHNK",
  },
  {
    product_code: "1106",
    slug: "lepal-pin---109",
    product_name: "LEPAL PIN - 10.9",
    category: "Accessories",
    short_description: "Lepal Pin 10.9",
    long_description: "Lepal Pin 10.9",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "lepal-pin---109_1.png",
    images: ["lepal-pin---109_1.png","lepal-pin---109_2.png"],
    product_link: "https://capapiesports.com/product_details/lepal-pin---109/6IXNXI6T0X",
  },
  {
    product_code: "1107",
    slug: "capapie-keychain",
    product_name: "CAPAPIE KEYCHAIN",
    category: "Accessories",
    short_description: "Capapie Keychain",
    long_description: "Capapie Keychain",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-keychain_1.png",
    images: ["capapie-keychain_1.png"],
    product_link: "https://capapiesports.com/product_details/capapie-keychain/UG7FOTSEST",
  },
  {
    product_code: "1112",
    slug: "tin-holder-pouch",
    product_name: "TIN HOLDER POUCH",
    category: "Accessories",
    short_description: "Tin Holder Pouch",
    long_description: "Tin Holder Pouch\n\nCapapie Sports and Equipment brings you its neoprene air rifle pellet box cover, engineered for superior safety and protection. Made from premium neoprene material, this cover offers exceptional durability and cushioning for your pellet box.\nThe cover features a secure zip closure, ensuring the pellets remain safely stored and easily accessible. Designed for both functionality and convenience, it provides robust protection against impacts.\nCapapie’s neoprene pellet box cover is the perfect storage solution for air Rifle and Pistol enthusiasts, combining safety, durability, and ease of use.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "tin-holder-pouch_1.png",
    images: ["tin-holder-pouch_1.png","tin-holder-pouch_2.png","tin-holder-pouch_3.png"],
    product_link: "https://capapiesports.com/product_details/tin-holder-pouch/HQOLGF9IVI",
  },
  {
    product_code: "1113",
    slug: "cylinder-pouch-rifle",
    product_name: "CYLINDER POUCH-RIFLE",
    category: "Accessories",
    short_description: "Cylinder Pouch Rifle",
    long_description: "Cylinder Pouch Rifle\n\nCapapie Sports and Equipment introduces its neoprene pistol cylinder cover, expertly designed for maximum safety and protection. Crafted from special neoprene material, this pouch ensures durability and cushioning for your pistol cylinder.\nThe pouch features Velcro fastenings for a secure and adjustable fit. Additionally, it is designed with a vent incorporating three slits, ensuring proper ventilation and preventing moisture buildup.\nCapapie’s neoprene pistol cylinder pouch combines safety, functionality, and convenience, making it an essential accessory for every shooter.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "cylinder-pouch-rifle_1.png",
    images: ["cylinder-pouch-rifle_1.png","cylinder-pouch-rifle_2.png","cylinder-pouch-rifle_3.png"],
    product_link: "https://capapiesports.com/product_details/cylinder-pouch-rifle/VUZRJOU4GJ",
  },
  {
    product_code: "1113",
    slug: "cylinder-pouch-pistol",
    product_name: "CYLINDER POUCH PISTOL",
    category: "Accessories",
    short_description: "Cylinder Pouch Pistol",
    long_description: "Cylinder Pouch Pistol",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "cylinder-pouch-pistol_1.png",
    images: ["cylinder-pouch-pistol_1.png"],
    product_link: "https://capapiesports.com/product_details/cylinder-pouch-pistol/FDPSRNB0ZN",
  },
  {
    product_code: "1117",
    slug: "capapie-suede-kneeling-roll-with-top-grip-rubber",
    product_name: "CAPAPIE SUEDE KNEELING ROLL WITH TOP GRIP RUBBER",
    category: "Accessories",
    short_description: "Capapie Suede Kneeling Roll with Top Grip Rubber",
    long_description: "Capapie Suede Kneeling Roll with Top Grip Rubber\n\nCapapie Sports and Equipment presents the Suede Kneeling Roll, engineered for superior stability and comfort during shooting. Filled with cork granules, it delivers excellent support for the kneeling position, ensuring precise aim and steady shooting. The roll features a unique outer surface made up of two strips of top grip material, enhancing durability and providing a secure, non-slip surface. It also includes a center-cut outer zipper and an internal stringed pouch to keep the cork granules securely in place, preventing spills. This product is designed for shooters seeking reliable and stable support for optimal performance.Capapie Sports and Equipment presents the Suede Kneeling Roll, engineered for superior stability and comfort during shooting. Filled with cork granules, it delivers excellent support for the kneeling position, ensuring precise aim and steady shooting. The roll features a unique outer surface made up of two strips of top grip material, enhancing durability and providing a secure, non-slip surface. It also includes a center-cut outer zipper and an internal stringed pouch to keep the cork granules securely in place, preventing spills. This product is designed for shooters seeking reliable and stable support for optimal performance.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-suede-kneeling-roll-with-top-grip-rubber_1.png",
    images: ["capapie-suede-kneeling-roll-with-top-grip-rubber_1.png","capapie-suede-kneeling-roll-with-top-grip-rubber_2.png","capapie-suede-kneeling-roll-with-top-grip-rubber_3.png","capapie-suede-kneeling-roll-with-top-grip-rubber_4.png"],
    product_link: "https://capapiesports.com/product_details/capapie-suede-kneeling-roll-with-top-grip-rubber/XQYJ4NAPNZ",
  },
  {
    product_code: "1118",
    slug: "capi-grip-kneeling-roll",
    product_name: "CAPI GRIP KNEELING ROLL",
    category: "Accessories",
    short_description: "Capi-Grip Kneeling Roll",
    long_description: "Capi-Grip Kneeling Roll\n\nCapapie Sports and Equipment proudly presents the Capi Grip Kneeling Roll with Top Grip and Suede. Designed for optimal stability and anti-slip with comfort, this roll is filled with cork granules to ensure reliable support while shooting.\nIts unique design features a suede surface for a soft, comfortable kneeling experience, while the top grip secures the roll in place during use. The roll is equipped with a half-moon outer zipper and an internal stringed pouch to prevent cork granules from spilling out.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capi-grip-kneeling-roll_1.png",
    images: ["capi-grip-kneeling-roll_1.png","capi-grip-kneeling-roll_2.png","capi-grip-kneeling-roll_3.png","capi-grip-kneeling-roll_4.png"],
    product_link: "https://capapiesports.com/product_details/capi-grip-kneeling-roll/YU4FAPZSSZ",
  },
  {
    product_code: "1119",
    slug: "capapie-top-grip-kneeling-roll",
    product_name: "CAPAPIE TOP GRIP KNEELING ROLL",
    category: "Accessories",
    short_description: "Top Grip Kneeling Roll",
    long_description: "Top Grip Kneeling Roll\n\nCapapie Sports and Equipment features the Top Grip Kneeling Roll, designed for unmatched stability and comfort during shooting. Filled with cork granules, this roll offers excellent support for the kneeling position, ensuring precise aim and steady shooting.\nThe product features a unique outer surface made of top grip material, enhancing durability and providing a secure, non-slip surface. It includes a center-cut outer zipper and an internal stringed pouch to keep cork granules securely in place and prevent spills.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-top-grip-kneeling-roll_1.png",
    images: ["capapie-top-grip-kneeling-roll_1.png","capapie-top-grip-kneeling-roll_2.png","capapie-top-grip-kneeling-roll_3.png","capapie-top-grip-kneeling-roll_4.png"],
    product_link: "https://capapiesports.com/product_details/capapie-top-grip-kneeling-roll/R2RLDEAQHN",
  },
  {
    product_code: "1120",
    slug: "capapie-handtowel",
    product_name: "CAPAPIE HANDTOWEL",
    category: "Accessories",
    short_description: "Capapie Handtowel",
    long_description: "Capapie Handtowel\n\nIntroducing the Capapie Shooting Towel – the perfect companion for shooters. Crafted from a blend of natural bamboo and cotton fibers, this towel offers exceptional softness and absorbency. The bamboo fibers ensure it is naturally odor-free and gentle on the skin, while the cotton provides durability and comfort. Designed to keep you dry and comfortable during intense shooting sessions, the Capapie Shooting Towel is an essential addition to your gear. Experience the perfect blend of nature and performance with this high-quality shooting towel, tailored to meet the demands of dedicated shooters.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-handtowel_1.png",
    images: ["capapie-handtowel_1.png","capapie-handtowel_2.png","capapie-handtowel_3.png","capapie-handtowel_4.png"],
    product_link: "https://capapiesports.com/product_details/capapie-handtowel/M7QJCOI9I8",
  },
  {
    product_code: "1122",
    slug: "nsg-dreamer-cap",
    product_name: "NSG DREAMER CAP",
    category: "Accessories",
    short_description: "NSG Dreamer Cap",
    long_description: "NSG Dreamer Cap",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "nsg-dreamer-cap_1.png",
    images: ["nsg-dreamer-cap_1.png","nsg-dreamer-cap_2.png","nsg-dreamer-cap_3.png"],
    product_link: "https://capapiesports.com/product_details/nsg-dreamer-cap/NMCQGDH1QJ",
  },
  {
    product_code: "1126",
    slug: "utility-box",
    product_name: "UTILITY BOX",
    category: "Accessories",
    short_description: "Utility Box",
    long_description: "Utility Box\n\nIntroducing the Multi Utility Kit Box by Capapie Sports and Equipment, a versatile and multi-functional storage solution for shooting enthusiasts. This robust box is designed to store all your essential shooting equipment securely. Inside, a foam pad ensures the safety and protection of your valuable gear. Whether you need to organize firearms, accessories, or other shooting essentials, the Multi Utility Kit Box offers the perfect blend of functionality and security. Keep your equipment safe and well-organized with this reliable and durable kit box.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "utility-box_1.png",
    images: ["utility-box_1.png","utility-box_2.png","utility-box_3.png","utility-box_4.png"],
    product_link: "https://capapiesports.com/product_details/utility-box/FRFEWTWGO1",
  },
  {
    product_code: "1131",
    slug: "black-cat-cap",
    product_name: "BLACK CAT CAP",
    category: "Accessories",
    short_description: "Black Cat Cap",
    long_description: "Black Cat Cap",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "black-cat-cap_1.png",
    images: ["black-cat-cap_1.png","black-cat-cap_2.png","black-cat-cap_3.png"],
    product_link: "https://capapiesports.com/product_details/black-cat-cap/CWY4MPGVMN",
  },
  {
    product_code: "1132",
    slug: "capi-grip-kneeling-pad",
    product_name: "CAPI GRIP KNEELING PAD",
    category: "Accessories",
    short_description: "Introducing the Capi Grip Kneeling Pad",
    long_description: "Introducing the Capi Grip Kneeling Pad\n\nIntroducing the Capi Grip Kneeling Pad by Capapie Sports and Equipment, engineered for superior stability and comfort. This pad features an HD PU foam core sandwiched between two layers of top grip material, with a precision cut-and-sew design that blends aesthetics with functionality. The expertly crafted cut-and-sew technique not only enhances grip and anti-slip performance but also ensures durability and longevity. The top grip material provides a secure, non-slip surface, offering reliable support during shooting positions. Additionally, the pad includes a loop holder for easy attachment to a utility bag, making it convenient to carry and access.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capi-grip-kneeling-pad_1.png",
    images: ["capi-grip-kneeling-pad_1.png","capi-grip-kneeling-pad_2.png","capi-grip-kneeling-pad_3.png","capi-grip-kneeling-pad_4.png"],
    product_link: "https://capapiesports.com/product_details/capi-grip-kneeling-pad/D1G91FDYKX",
  },
  {
    product_code: "1133",
    slug: "top-grip-kneeling-pad",
    product_name: "TOP GRIP KNEELING PAD",
    category: "Accessories",
    short_description: "Top Grip Kneeling Pad",
    long_description: "Top Grip Kneeling Pad\n\nCapapie Sports and Equipment produces the Top Grip Kneeling Pad, designed to provide exceptional stability and comfort during shooting. This pad features an HD PU foam core sandwiched between two layers of durable top grip material, ensuring reliable support and a secure, non-slip surface.\nThe unique top grip outer surface enhances durability and stability, making it ideal for precise shooting positions. Additionally, the pad includes a convenient loop holder, allowing shooters to easily attach it to their utility bag for effortless transport.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "top-grip-kneeling-pad_1.png",
    images: ["top-grip-kneeling-pad_1.png","top-grip-kneeling-pad_2.png","top-grip-kneeling-pad_3.png","top-grip-kneeling-pad_4.png"],
    product_link: "https://capapiesports.com/product_details/top-grip-kneeling-pad/NHYNVFQSHG",
  },
  {
    product_code: "1033",
    slug: "turtle-mini-sub-bag",
    product_name: "TURTLE MINI SUB BAG",
    category: "Bags",
    short_description: "The perfect all-in-one packing solution for pistol shooters. It comes with pistol storage, a laptop storage compartment, and a separate shooting shoe compartment. The front zipper opening is equipped with an organizer. It is ultra-light in ",
    long_description: "The perfect all-in-one packing solution for pistol shooters. It comes with pistol storage, a laptop storage compartment, and a separate shooting shoe compartment. The front zipper opening is equipped with an organizer. It is ultra-light in weight with robust construction and a retractable aluminum handle with a comfortable grip.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "turtle-mini-sub-bag_1.jpg",
    images: ["turtle-mini-sub-bag_1.jpg","turtle-mini-sub-bag_2.jpg","turtle-mini-sub-bag_3.jpg"],
    product_link: "https://capapiesports.com/product_details/turtle-mini-sub-bag/6EV5P2TE0V",
  },
  {
    product_code: "1034",
    slug: "row-sports-bag",
    product_name: "ROW SPORTS BAG",
    category: "Bags",
    short_description: "Rifle On Wheels",
    long_description: "Rifle On Wheels\n\nKey Features of ROW\nWater Resistance\nHigh tensile strength & ball bearing in wheels for easy pulling, with heavy loads\nAvailable in 3 vibrant colours (Red, Green, Sky Blue)\nExtended rifle holding compartment\nProduct Details of ROW\nDimensions - L - 75 cm, W - 40 cm, H - 45 cm, Actual Weight - 5.7 Kg\n2 side pocket\n1 inside top document pocket\n2  zip mesh pocket\n3 Compartments - 1) Big compartment for jacket/ trouser 2) Rifle compartment 3) Top compartment for shoes & accessories\n2 Strong Plastic duraline wheels\nMaterial - Water repellent Polyester\nWarranty - 1 year",
    features: [],
    colors: [],
    sizing: "Available in 3 vibrant colours (Red, Green, Sky Blue)",
    image_filename: "row-sports-bag_1.png",
    images: ["row-sports-bag_1.png","row-sports-bag_2.png","row-sports-bag_3.png"],
    product_link: "https://capapiesports.com/product_details/row-sports-bag/HBCLQ6IBFX",
  },
  {
    product_code: "1037",
    slug: "capapie-jacket-trouser-kit-bag",
    product_name: "CAPAPIE JACKET TROUSER KIT BAG",
    category: "Bags",
    short_description: "Capapie Jacket Trouser Kit Bag",
    long_description: "Capapie Jacket Trouser Kit Bag",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-jacket-trouser-kit-bag_1.png",
    images: ["capapie-jacket-trouser-kit-bag_1.png","capapie-jacket-trouser-kit-bag_2.png"],
    product_link: "https://capapiesports.com/product_details/capapie-jacket-trouser-kit-bag/MALMN3F461",
  },
  {
    product_code: "1039",
    slug: "capapie-shoe-bag",
    product_name: "CAPAPIE SHOE BAG",
    category: "Bags",
    short_description: "Capapie Shoe Bag",
    long_description: "Capapie Shoe Bag",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capapie-shoe-bag_1.png",
    images: ["capapie-shoe-bag_1.png"],
    product_link: "https://capapiesports.com/product_details/capapie-shoe-bag/47I4X1NG0F",
  },
  {
    product_code: "1077",
    slug: "shooters-range-bag",
    product_name: "SHOOTERS RANGE BAG",
    category: "Bags",
    short_description: "Another design is also available without Capapie 10.9 metal buttons.",
    long_description: "Another design is also available without Capapie 10.9 metal buttons.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "shooters-range-bag_1.png",
    images: ["shooters-range-bag_1.png","shooters-range-bag_2.png","shooters-range-bag_3.png","shooters-range-bag_4.png"],
    product_link: "https://capapiesports.com/product_details/shooters-range-bag/NBUYGVKBOH",
  },
  {
    product_code: "1078",
    slug: "shooters-range-bag-with-outer-pocket",
    product_name: "SHOOTERS RANGE BAG (WITH OUTER POCKET)",
    category: "Bags",
    short_description: "A must-have for every serious target shooter. This is made of the same materials as your Jacket and Trousers. It is fitted with Capapie 10.9 metal buttons. It can accommodate your day-to-day nick-knack like mobile phones & chargers, power b",
    long_description: "A must-have for every serious target shooter. This is made of the same materials as your Jacket and Trousers. It is fitted with Capapie 10.9 metal buttons. It can accommodate your day-to-day nick-knack like mobile phones & chargers, power banks, iPads, tablets, etc.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "shooters-range-bag-with-outer-pocket_1.png",
    images: ["shooters-range-bag-with-outer-pocket_1.png","shooters-range-bag-with-outer-pocket_2.png","shooters-range-bag-with-outer-pocket_3.png"],
    product_link: "https://capapiesports.com/product_details/shooters-range-bag-with-outer-pocket/0WNHT2YWNL",
  },
  {
    product_code: "1114",
    slug: "nsg-jacket-and-trouser-kit-bag",
    product_name: "NSG JACKET AND TROUSER KIT BAG",
    category: "Bags",
    short_description: "NSG Kit Bag",
    long_description: "NSG Kit Bag\n\nCapapie Sports and Equipment presents a kit bag designed for our world-famous NSG jacket trousers. It features compartments for a shooting jacket, trousers, and an inner set. The lightweight bag includes a utility hook for carrying gear during competitions.\nThe bag has space for shoes, accommodating all the essentials a shooter needs. A Velcro-attached section allows for name tags or other identification markers, adding a personal touch.\nCapapie’s kit bag offers a practical, organized storage solution, ensuring that every item has its place. It combines functionality with innovation for peak performance and is ideal for training and competitions.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "nsg-jacket-and-trouser-kit-bag_1.png",
    images: ["nsg-jacket-and-trouser-kit-bag_1.png","nsg-jacket-and-trouser-kit-bag_2.png","nsg-jacket-and-trouser-kit-bag_3.png"],
    product_link: "https://capapiesports.com/product_details/nsg-jacket-and-trouser-kit-bag/DNWUKK4YTX",
  },
  {
    product_code: "1021",
    slug: "premium-cut-finger-shooting-glove",
    product_name: "PREMIUM CUT FINGER SHOOTING GLOVE",
    category: "Gloves",
    short_description: "Premium Cut Finger Glove is designed with black anti-slip rubber, mesh material for better circulation of air.",
    long_description: "Premium Cut Finger Glove is designed with black anti-slip rubber, mesh material for better circulation of air.\n\nColor: Black\nSizes : XS | S | M | L | XL | XXL",
    features: [],
    colors: [{"label":"Color","values":["Black"]}],
    sizing: "",
    image_filename: "premium-cut-finger-shooting-glove_1.jpg",
    images: ["premium-cut-finger-shooting-glove_1.jpg","premium-cut-finger-shooting-glove_2.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-cut-finger-shooting-glove/CVWJTFGWTB",
  },
  {
    product_code: "1025",
    slug: "topline-cut-finger-shooting-glove",
    product_name: "TOPLINE CUT FINGER SHOOTING GLOVE",
    category: "Gloves",
    short_description: "Topline Cut Finger Glove is designed with black anti-slip rubber, mesh material for better circulation of air, and thick leather piping along the edges.",
    long_description: "Topline Cut Finger Glove is designed with black anti-slip rubber, mesh material for better circulation of air, and thick leather piping along the edges.\n\nColor: Black\nSizes : XS | S | M | L | XL | XXL",
    features: [],
    colors: [{"label":"Color","values":["Black"]}],
    sizing: "",
    image_filename: "topline-cut-finger-shooting-glove_1.jpg",
    images: ["topline-cut-finger-shooting-glove_1.jpg","topline-cut-finger-shooting-glove_2.jpg"],
    product_link: "https://capapiesports.com/product_details/topline-cut-finger-shooting-glove/EV7B4WIEQ6",
  },
  {
    product_code: "1079",
    slug: "capiglo-top-grip-glove",
    product_name: "CAPIGLO TOP GRIP GLOVE",
    category: "Gloves",
    short_description: "Elastic wristband for close fitting around the wrist as per ISSF rule number 7.5.6.2",
    long_description: "1. Elastic wristband for close fitting around the wrist as per ISSF rule number 7.5.6.2\n\n1. Easy to wear and easy to remove\n2. Anatomically designed cut for better performance.\n3. Entirely handcrafted piping for a robust feel.\n4. “SWEAT FREE” Material used on finger surface.\n5. The entire TOP GRIP surface is provided with genuine leather for better grip.\n6. Inner Lining for sweat-absorbing material with entire padding.\n7. Finger Slot provided below TOP GRIP padding for ease of wearing.\n8. Two finger-straps for easy removal of glove.\nLeather Color: Blue | Black | Red | Yellow | Pink | Grey | Green | Orange\nSizes: XS | S | M | L | XL | XXL",
    features: ["Elastic wristband for close fitting around the wrist as per ISSF rule number 7.5.6.2","Easy to wear and easy to remove","Anatomically designed cut for better performance.","Entirely handcrafted piping for a robust feel.","“SWEAT FREE” Material used on finger surface.","The entire TOP GRIP surface is provided with genuine leather for better grip.","Inner Lining for sweat-absorbing material with entire padding.","Finger Slot provided below TOP GRIP padding for ease of wearing.","Two finger-straps for easy removal of glove."],
    colors: [{"label":"Leather Color","values":["Blue","Black","Red","Yellow","Pink","Grey","Green","Orange"]}],
    sizing: "",
    image_filename: "capiglo-top-grip-glove_1.jpg",
    images: ["capiglo-top-grip-glove_1.jpg","capiglo-top-grip-glove_2.jpg"],
    product_link: "https://capapiesports.com/product_details/capiglo-top-grip-glove/IIGF9XSYI5",
  },
  {
    product_code: "1096",
    slug: "gt-109-trigger-glove",
    product_name: "G.T 10.9 TRIGGER GLOVE",
    category: "Gloves",
    short_description: "Perfect Grip: The silicon-studded gripper on the palm area ensures a perfect grip, allowing you to maintain control of your firearm with ease.",
    long_description: "G.T 10.9 Trigger Glove\n\nIntroducing GT (10.9) Gripping & Triggering Glove.\nWe are excited to introduce GT Curve, the ultimate shooting trigger glove designed to enhance your performance on the range. Crafted with precision and powered by HEIQ and PURE Swiss technology, GT Curve is more than just a glove—it's your second skin.\nKey features of the GT Curve include:\n1.            Perfect Grip: The silicon-studded gripper on the palm area ensures a perfect grip, allowing you to maintain control of your firearm with ease.\n2.            GT Curve Design: The curve carved in the triggering finger, known as the GT Curve, ensures a seamless trigger pull without any creases or wrinkles, providing the highest level of precision and comfort.\n3.            Anatomical Fit: The glove is anatomically designed to provide a snug fit, ensuring maximum comfort and flexibility during shooting.\n4.            Thermo Control: The Swiss technology used in GT Curve provides thermo control, maintaining the palm temperature in both warm and cold weather conditions.\n5.            Odor Control and Anti-microbial: The glove is equipped with HEIQ and PURE Swiss technology for odor control and anti-microbial properties, ensuring freshness and hygiene.\n6.            Ergonomic Stitching: Ergonomically stitched to minimize creases at the palm area, the glove provides a smooth and comfortable fit.\n7.            Easy to Wear: The pull-on tab and pull-off strings make it easy to wear and remove the glove, providing convenience without compromising on performance.\nGT Curve is the result of extensive research and development, with input from coaches and top shooters to ensure every aspect of the glove is thoughtfully designed. The 10.9 context of the glove represents the highest level of precision, gripping, and triggering, making it the perfect choice for competitive shooters.\nExperience the ultimate in shooting comfort and performance with GT (10.9)glove",
    features: ["Perfect Grip: The silicon-studded gripper on the palm area ensures a perfect grip, allowing you to maintain control of your firearm with ease.","GT Curve Design: The curve carved in the triggering finger, known as the GT Curve, ensures a seamless trigger pull without any creases or wrinkles, providing the highest level of precision and comfort.","Anatomical Fit: The glove is anatomically designed to provide a snug fit, ensuring maximum comfort and flexibility during shooting.","Thermo Control: The Swiss technology used in GT Curve provides thermo control, maintaining the palm temperature in both warm and cold weather conditions.","Odor Control and Anti-microbial: The glove is equipped with HEIQ and PURE Swiss technology for odor control and anti-microbial properties, ensuring freshness and hygiene.","Ergonomic Stitching: Ergonomically stitched to minimize creases at the palm area, the glove provides a smooth and comfortable fit.","Easy to Wear: The pull-on tab and pull-off strings make it easy to wear and remove the glove, providing convenience without compromising on performance."],
    colors: [],
    sizing: "",
    image_filename: "gt-109-trigger-glove_1.png",
    images: ["gt-109-trigger-glove_1.png","gt-109-trigger-glove_2.png"],
    product_link: "https://capapiesports.com/product_details/gt-109-trigger-glove/THOPRN5IR2",
  },
  {
    product_code: "1103",
    slug: "capifit-i-glove",
    product_name: "CAPIFIT-I GLOVE",
    category: "Gloves",
    short_description: "Foam Padded Slip-Resistant 'Top Grip': The foam-padded 'Top Grip' ensures a slip-resistant hold on your rifle, providing stability and control during shooting.",
    long_description: "CapiFit- I Glove\n\nIntroducing Capi Fit 1: The Ultimate Air Rifle Shooting Glove\nWe are excited to introduce Capi Fit 1, the ultimate air rifle shooting glove designed to elevate your performance on the range. Crafted with precision and innovation, Capi Fit 1 is more than just a glove—it's your secret weapon for success.\nKey features of Capi Fit 1 include:\n1.            Foam Padded Slip-Resistant 'Top Grip': The foam-padded 'Top Grip' ensures a slip-resistant hold on your rifle, providing stability and control during shooting.\n2.            Capapie Branded Pull-Off Straps: The branded pull-off straps add an elegant touch to the glove and make it easy to wear and remove.\n3.            Highly Breathable Ventilation: The glove is highly breathable, ensuring optimal airflow and comfort during long shooting sessions.\n4.            Double Foam Padded for Stress-Free Holding: The double foam padding provides stress-free holding and easy-to-grip functionality, enhancing your shooting experience.\n5.            Capapie Branded PVC Badge: The PVC badge adds a touch of elegance to the glove, showcasing the Capapie brand.\n6.            Wrist Grip with Comfort and Support: The wrist grip provides comfort and support, ensuring a secure fit and reducing fatigue during shooting.\n7.            Power Elastic with Branded Pull-On Straps: The power elastic and branded pull-on straps ensure a strong and secure fit, allowing for a smooth and comfortable shooting experience.\n8.            Soft Padded for Rifle Holding and Cushions: The soft padding provides a cushioned feel for perfect and comfortable shooting, reducing strain on your hands and wrists.\n9.            1.4 to 1.6 mm High-End Milled Nappa Leather: The glove is made from high-end milled Nappa leather, providing durability and a luxurious feel.\n10.         Slip-Resistant 'Top Grip' for Rifle Holding Position: The slip-resistant 'Top Grip' ensures a secure hold on your rifle, allowing for precise and accurate shooting.\nExperience the ultimate in shooting comfort and performance with Capi Fit 1.",
    features: ["Foam Padded Slip-Resistant 'Top Grip': The foam-padded 'Top Grip' ensures a slip-resistant hold on your rifle, providing stability and control during shooting.","Capapie Branded Pull-Off Straps: The branded pull-off straps add an elegant touch to the glove and make it easy to wear and remove.","Highly Breathable Ventilation: The glove is highly breathable, ensuring optimal airflow and comfort during long shooting sessions.","Double Foam Padded for Stress-Free Holding: The double foam padding provides stress-free holding and easy-to-grip functionality, enhancing your shooting experience.","Capapie Branded PVC Badge: The PVC badge adds a touch of elegance to the glove, showcasing the Capapie brand.","Wrist Grip with Comfort and Support: The wrist grip provides comfort and support, ensuring a secure fit and reducing fatigue during shooting.","Power Elastic with Branded Pull-On Straps: The power elastic and branded pull-on straps ensure a strong and secure fit, allowing for a smooth and comfortable shooting experience.","Soft Padded for Rifle Holding and Cushions: The soft padding provides a cushioned feel for perfect and comfortable shooting, reducing strain on your hands and wrists.","1.4 to 1.6 mm High-End Milled Nappa Leather: The glove is made from high-end milled Nappa leather, providing durability and a luxurious feel.","Slip-Resistant 'Top Grip' for Rifle Holding Position: The slip-resistant 'Top Grip' ensures a secure hold on your rifle, allowing for precise and accurate shooting."],
    colors: [],
    sizing: "",
    image_filename: "capifit-i-glove_1.png",
    images: ["capifit-i-glove_1.png","capifit-i-glove_2.png","capifit-i-glove_3.png","capifit-i-glove_4.png"],
    product_link: "https://capapiesports.com/product_details/capifit-i-glove/7OCXBAO9TR",
  },
  {
    product_code: "1109",
    slug: "capiglo--glove",
    product_name: "CAPIGLO + GLOVE",
    category: "Gloves",
    short_description: "Automatic Cooling Feature: The cool gel foam provides an automatic cooling feature, ensuring a consistently fresh and comfortable palm while shooting.",
    long_description: "CapiGlo + Glove\n\nTitle: Introducing CAPI GLOVE+: The Ultimate Shooting Glove with Swiss Tech Inside\nWe are excited to introduce CAPI GLOVE+, the ultimate shooting glove designed to elevate your performance on the range. Featuring Swiss tech inside for thermo regulation, anti-microbial properties, and odor control, CAPI GLOVE+ is more than just a glove—it's your secret weapon for success.\nKey features of the CAPI GLOVE+ include:\n1.            Automatic Cooling Feature: The cool gel foam provides an automatic cooling feature, ensuring a consistently fresh and comfortable palm while shooting.\n2.            Soft and Comfortable Leather Pull-Off Straps: The soft and comfortable leather pull-off straps make it easy to use, allowing for quick removal of the glove during breaks.\n3.            Anatomically Cut Design: The glove is anatomically designed to provide a snug fit, ensuring maximum comfort and flexibility during shooting.\n4.            Grip Rubber Surface: The grip rubber surface ensures a better grip in all shooting positions, enhancing your accuracy and control.\n5.            Elastic Wrist Band with Branding: The elastic wristband with branding provides more support and a close fitting around the wrist area, as per ISSF rule number 7.5.6.2.\nExperience the ultimate in shooting comfort and performance with CAPI GLO+. Visit our website or stop by our store to try on a pair today.",
    features: ["Automatic Cooling Feature: The cool gel foam provides an automatic cooling feature, ensuring a consistently fresh and comfortable palm while shooting.","Soft and Comfortable Leather Pull-Off Straps: The soft and comfortable leather pull-off straps make it easy to use, allowing for quick removal of the glove during breaks.","Anatomically Cut Design: The glove is anatomically designed to provide a snug fit, ensuring maximum comfort and flexibility during shooting.","Grip Rubber Surface: The grip rubber surface ensures a better grip in all shooting positions, enhancing your accuracy and control.","Elastic Wrist Band with Branding: The elastic wristband with branding provides more support and a close fitting around the wrist area, as per ISSF rule number 7.5.6.2."],
    colors: [],
    sizing: "",
    image_filename: "capiglo--glove_1.png",
    images: ["capiglo--glove_1.png","capiglo--glove_2.png","capiglo--glove_3.png","capiglo--glove_4.png"],
    product_link: "https://capapiesports.com/product_details/capiglo--glove/A1YULQ7MCW",
  },
  {
    product_code: "1075",
    slug: "capiflex-shooting-upper",
    product_name: "CAPIFLEX SHOOTING UPPER",
    category: "Inners",
    short_description: "We have developed CAPIFLEX® inner to be worn inside your shooting Jacket and Trouser.",
    long_description: "1. We have developed CAPIFLEX® inner to be worn inside your shooting Jacket and Trouser.\n\n1. This complies with ISSF rule number 7.5.2.1. CAPIFLEX® is highly breathable, lightweight, and stretches in all directions.\n2. CAPIFLEX® shooting upper has extra an layer of CAPIFLEX® fabric at the elbow and shoulder for comfort in all shooting positions.\n3. The upper is designed like a pullover with a full-length YKK zipper for easy wear.\n4. CAPIFLEX shooting upper is a blend of CAPIFLEX and Lycra.\n5. Sweat-free fabric is inherently very thin and wrinkle-free. Hence, it is used on the inner elbows to enhance comfort in all shooting positions.\n6.CAPIFLEX® shooting lowers are designed for maximum comfort and have drawstrings and elasticized waistbands.\nMaterial Color: Black\nMale/Female Sizes : XS | S | M | XL | XXL",
    features: ["We have developed CAPIFLEX® inner to be worn inside your shooting Jacket and Trouser.","This complies with ISSF rule number 7.5.2.1. CAPIFLEX® is highly breathable, lightweight, and stretches in all directions.","CAPIFLEX® shooting upper has extra an layer of CAPIFLEX® fabric at the elbow and shoulder for comfort in all shooting positions.","The upper is designed like a pullover with a full-length YKK zipper for easy wear.","CAPIFLEX shooting upper is a blend of CAPIFLEX and Lycra.","Sweat-free fabric is inherently very thin and wrinkle-free. Hence, it is used on the inner elbows to enhance comfort in all shooting positions.","CAPIFLEX® shooting lowers are designed for maximum comfort and have drawstrings and elasticized waistbands."],
    colors: [{"label":"Material Color","values":["Black"]}],
    sizing: "",
    image_filename: "capiflex-shooting-upper_1.png",
    images: ["capiflex-shooting-upper_1.png"],
    product_link: "https://capapiesports.com/product_details/capiflex-shooting-upper/RFSHOZZFWZ",
  },
  {
    product_code: "1076",
    slug: "capiflex-shooting-lower",
    product_name: "CAPIFLEX SHOOTING LOWER",
    category: "Inners",
    short_description: "We have developed CAPIFLEX® inner to be worn inside your shooting Jacket and Trouser.",
    long_description: "1. We have developed CAPIFLEX® inner to be worn inside your shooting Jacket and Trouser.\n\n1. This complies with ISSF rule number 7.5.2.1. CAPIFLEX® is highly breathable, lightweight, and stretches in all directions.\n2. CAPIFLEX® shooting upper has extra an layer of CAPIFLEX® fabric at the elbow and shoulder for comfort in all shooting positions.\n3. The upper is designed like a pullover with a full-lenght YKK zipper for easy wear.\n4. CAPIFLEX shooting upper is a blend of CAPIFLEX and Lycra.\n5. Sweat free fabric is inherently very thin and wrinkle free. Hence, it is used on the inner elbows to enhance comfort in all shooting positions.\n6. CAPIFLEX® shooting lowers are designed for maximum comfort and have draw strings and elasticized waistband.\nMaterial Color : Black\nMale/Female Sizes : XS | S | M | XL | XXL",
    features: ["We have developed CAPIFLEX® inner to be worn inside your shooting Jacket and Trouser.","This complies with ISSF rule number 7.5.2.1. CAPIFLEX® is highly breathable, lightweight, and stretches in all directions.","CAPIFLEX® shooting upper has extra an layer of CAPIFLEX® fabric at the elbow and shoulder for comfort in all shooting positions.","The upper is designed like a pullover with a full-lenght YKK zipper for easy wear.","CAPIFLEX shooting upper is a blend of CAPIFLEX and Lycra.","Sweat free fabric is inherently very thin and wrinkle free. Hence, it is used on the inner elbows to enhance comfort in all shooting positions.","CAPIFLEX® shooting lowers are designed for maximum comfort and have draw strings and elasticized waistband."],
    colors: [{"label":"Material Color","values":["Black"]}],
    sizing: "",
    image_filename: "capiflex-shooting-lower_1.png",
    images: ["capiflex-shooting-lower_1.png"],
    product_link: "https://capapiesports.com/product_details/capiflex-shooting-lower/BCSQ3HIVVG",
  },
  {
    product_code: "1097",
    slug: "pro-shooting-upper",
    product_name: "PRO SHOOTING UPPER",
    category: "Inners",
    short_description: "Pro Inners Upper",
    long_description: "Pro Inners Upper\n\nIntroducing the Pro Inner by Capapie Sports and Equipment, designed for peak performance and comfort. This advanced innerwear features a double-layer padded sleeve for enhanced protection and a compressing fit for superior support. Its highly breathable fabric ensures optimal airflow while moisture-wicking properties keep you dry and comfortable during intense activities. Experience the perfect blend of functionality and comfort with the Pro Inner, tailored to meet the needs of dedicated athletes.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "pro-shooting-upper_1.png",
    images: ["pro-shooting-upper_1.png","pro-shooting-upper_2.png"],
    product_link: "https://capapiesports.com/product_details/pro-shooting-upper/HS9SLLWZCW",
  },
  {
    product_code: "1098",
    slug: "pro-shooting-lower",
    product_name: "PRO SHOOTING LOWER",
    category: "Inners",
    short_description: "Pro Inners Lower",
    long_description: "Pro Inners Lower\n\nIntroducing the Pro Inner by Capapie Sports and Equipment, designed for peak performance and comfort. This advanced innerwear features a double-layer padded sleeve for enhanced protection and a compressing fit for superior support. Its highly breathable fabric ensures optimal airflow while moisture-wicking properties keep you dry and comfortable during intense activities. Experience the perfect blend of functionality and comfort with the Pro Inner, tailored to meet the needs of dedicated athletes.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "pro-shooting-lower_1.png",
    images: ["pro-shooting-lower_1.png","pro-shooting-lower_2.png"],
    product_link: "https://capapiesports.com/product_details/pro-shooting-lower/1W55U86QZL",
  },
  {
    product_code: "1115",
    slug: "capiflex--shooting-upper",
    product_name: "CAPIFLEX + SHOOTING UPPER",
    category: "Inners",
    short_description: "Capiflex + Inners Upper",
    long_description: "Capiflex + Inners Upper\n\nCapiflex+: The Pinnacle of Comfort and Performance for Competitive Rifle Shooters\nOverview\nIn the highly precise and demanding sport of rifle shooting, every detail matters. Athletes competing at national and international levels need gear that not only supports their performance but also provides the utmost comfort. Capiflex+ has been designed with these exact needs in mind. Worn under the shooting jacket and trousers, this innovative inner set provides unparalleled support and comfort, ensuring athletes can focus entirely on their performance.\nUnique Selling Points\n1.\nPerfect Companion for Capapie Shooting Costumes: Capiflex+ is specifically designed to be worn under Capapie shooting costumes. The integration of these garments provides a seamless experience for the athlete, enhancing overall performance and comfort.\n2.\nPremium Fabric: Made from Capiflex premium fabric, this inner set offers the perfect balance of support and comfort. The thick material holds the body tight, ensuring a snug fit that aids stability during shooting.\n3.\nAdvanced Breathability and Comfort: Utilizing modern technology, Capiflex+ is extremely breathable and body-hugging. The fabric ensures that athletes remain cool and comfortable, even during intense competitions.\n4.\nHEIQ PURE Powered: The Capiflex+ product is enhanced with HEIQ PURE, a state-of-the-art antimicrobial fabric technology that keeps athletes fresh and ready to perform at their best. This technology helps in maintaining hygiene by preventing the growth of bacteria that cause odors.\n5.\nOdor Control with Citrus Essence: One of the standout features of Capiflex+ is its built-in odor control. Infused with a citrus essence, the fabric controls body odor caused by sweat, ensuring athletes feel and smell clean throughout their performance.\n6.\nAdditional Padding for Key Areas: The inner set includes double-layered padding at the elbows and knees. This feature is crucial for providing extra comfort and protection in prone and kneeling positions, which are common in rifle shooting.\n7.\nReduced Risk of \"Throbbing Pulse\": The innovative technology of Capiflex+ helps reduce the risk of experiencing a “throbbing pulse,” often caused by the shooting sling in kneeling and prone positions. This feature ensures that athletes maintain steady and accurate aim.\n8.\nSnug Fit and Durability: The Capiflex+ inner set fits snugly, keeping the body fresh, windproof, and abrasion-resistant. This durability ensures long-term use without compromising on comfort or performance.\n9.\nSeamless Design for Ultimate Comfort: The inner set is designed to feel seamless, providing a soft and secure fit that avoids irritating pressure points. This ensures that athletes can wear Capiflex+ for extended periods without discomfort.\n10.\nEnhanced Design: Featuring the 7circle Capapie design and a 10.9 target print, the aesthetic enhancements of the Capiflex+ inner set not only look great but also add to the overall experience of wearing it.\nTechnical Specifications\n•\nMaterial Composition: Capiflex+ is crafted from a high-performance blend of synthetic fibers that provide durability, flexibility, and comfort.\n•\nAnti-Microbial Treatment: Treated with HEIQ PURE, the fabric prevents the growth of odor-causing bacteria, keeping athletes fresh.\n•\nBreathable and Moisture-Wicking: The fabric’s advanced breathability and moisture-wicking properties ensure that athletes stay dry and comfortable.\n•\nDouble-Layered Padding: Additional padding at elbows and knees provides extra protection and comfort in key positions.\n•\nSeamless Design: The seamless construction eliminates pressure points and irritation, offering unmatched comfort.\nBenefits for Rifle Shooting Athletes\n1.\nStability and Precision: The tight fit and additional padding of Capiflex+ help maintain stability and reduce unnecessary movements, which are crucial for accurate shooting.\n2.\nEnhanced Comfort: The breathable, moisture-wicking fabric and seamless design ensure maximum comfort, allowing athletes to focus solely on their performance.\n3.\nOdor Control: The citrus essence and antimicrobial treatment keep the athlete feeling fresh and confident, even during extended competitions.\n4.\nDurability: The abrasion-resistant and windproof properties ensure that Capiflex+ stands up to the rigors of competitive use, providing long-lasting support and comfort.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capiflex--shooting-upper_1.png",
    images: ["capiflex--shooting-upper_1.png","capiflex--shooting-upper_2.png","capiflex--shooting-upper_3.png","capiflex--shooting-upper_4.png"],
    product_link: "https://capapiesports.com/product_details/capiflex--shooting-upper/7Z4NKYOKP7",
  },
  {
    product_code: "1116",
    slug: "capiflex--shooting-lower",
    product_name: "CAPIFLEX + SHOOTING LOWER",
    category: "Inners",
    short_description: "Capiflex + Shooting Inners Lower",
    long_description: "Capiflex + Shooting Inners Lower\n\nCapiflex+: The Pinnacle of Comfort and Performance for Competitive Rifle Shooters\nOverview\nIn the highly precise and demanding sport of rifle shooting, every detail matters. Athletes competing at national and international levels need gear that not only supports their performance but also provides the utmost comfort. Capiflex+ has been designed with these exact needs in mind. Worn under the shooting jacket and trousers, this innovative inner set provides unparalleled support and comfort, ensuring athletes can focus entirely on their performance.\nUnique Selling Points\n1.\nPerfect Companion for Capapie Shooting Costumes: Capiflex+ is specifically designed to be worn under Capapie shooting costumes. The integration of these garments provides a seamless experience for the athlete, enhancing overall performance and comfort.\n2.\nPremium Fabric: Made from Capiflex premium fabric, this inner set offers the perfect balance of support and comfort. The thick material holds the body tight, ensuring a snug fit that aids stability during shooting.\n3.\nAdvanced Breathability and Comfort: Utilizing modern technology, Capiflex+ is extremely breathable and body-hugging. The fabric ensures that athletes remain cool and comfortable, even during intense competitions.\n4.\nHEIQ PURE Powered: The Capiflex+ product is enhanced with HEIQ PURE, a state-of-the-art antimicrobial fabric technology that keeps athletes fresh and ready to perform at their best. This technology helps in maintaining hygiene by preventing the growth of bacteria that cause odors.\n5.\nOdor Control with Citrus Essence: One of the standout features of Capiflex+ is its built-in odor control. Infused with a citrus essence, the fabric controls body odor caused by sweat, ensuring athletes feel and smell clean throughout their performance.\n6.\nAdditional Padding for Key Areas: The inner set includes double-layered padding at the elbows and knees. This feature is crucial for providing extra comfort and protection in prone and kneeling positions, which are common in rifle shooting.\n7.\nReduced Risk of \"Throbbing Pulse\": The innovative technology of Capiflex+ helps reduce the risk of experiencing a “throbbing pulse,” often caused by the shooting sling in kneeling and prone positions. This feature ensures that athletes maintain steady and accurate aim.\n8.\nSnug Fit and Durability: The Capiflex+ inner set fits snugly, keeping the body fresh, windproof, and abrasion-resistant. This durability ensures long-term use without compromising on comfort or performance.\n9.\nSeamless Design for Ultimate Comfort: The inner set is designed to feel seamless, providing a soft and secure fit that avoids irritating pressure points. This ensures that athletes can wear Capiflex+ for extended periods without discomfort.\n10.\nEnhanced Design: Featuring the 7circle Capapie design and a 10.9 target print, the aesthetic enhancements of the Capiflex+ inner set not only look great but also add to the overall experience of wearing it.\nTechnical Specifications\n•\nMaterial Composition: Capiflex+ is crafted from a high-performance blend of synthetic fibers that provide durability, flexibility, and comfort.\n•\nAnti-Microbial Treatment: Treated with HEIQ PURE, the fabric prevents the growth of odor-causing bacteria, keeping athletes fresh.\n•\nBreathable and Moisture-Wicking: The fabric’s advanced breathability and moisture-wicking properties ensure that athletes stay dry and comfortable.\n•\nDouble-Layered Padding: Additional padding at elbows and knees provides extra protection and comfort in key positions.\n•\nSeamless Design: The seamless construction eliminates pressure points and irritation, offering unmatched comfort.\nBenefits for Rifle Shooting Athletes\n1.\nStability and Precision: The tight fit and additional padding of Capiflex+ help maintain stability and reduce unnecessary movements, which are crucial for accurate shooting.\n2.\nEnhanced Comfort: The breathable, moisture-wicking fabric and seamless design ensure maximum comfort, allowing athletes to focus solely on their performance.\n3.\nOdor Control: The citrus essence and antimicrobial treatment keep the athlete feeling fresh and confident, even during extended competitions.\n4.\nDurability: The abrasion-resistant and windproof properties ensure that Capiflex+ stands up to the rigors of competitive use, providing long-lasting support and comfort.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "capiflex--shooting-lower_1.png",
    images: ["capiflex--shooting-lower_1.png","capiflex--shooting-lower_2.png","capiflex--shooting-lower_3.png"],
    product_link: "https://capapiesports.com/product_details/capiflex--shooting-lower/UTLLGKP0MK",
  },
  {
    product_code: "1003",
    slug: "pro-high-quality-canvas-jacket",
    product_name: "PRO HIGH QUALITY CANVAS JACKET",
    category: "Jackets & Trousers",
    short_description: "The Pro high-quality canvas jacket and trousers is a kit for the beginner serious target shooter.",
    long_description: "1. The Pro high-quality canvas jacket and trousers is a kit for the beginner serious target shooter.\n2. It has a perfectly customized anatomical cut, which provides increased stability, and fine quality double canvas gives the shooter the required edge.\n\nCanvas : Black | Red | Grey | Blue | Green | Sky Blue | Pink | Turquoise | Purple\nLeather & Piping Color : Black | Red | Green | White | Yellow |Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE",
    features: ["The Pro high-quality canvas jacket and trousers is a kit for the beginner serious target shooter.","It has a perfectly customized anatomical cut, which provides increased stability, and fine quality double canvas gives the shooter the required edge."],
    colors: [{"label":"Leather & Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE",
    image_filename: "pro-high-quality-canvas-jacket_1.jpg",
    images: ["pro-high-quality-canvas-jacket_1.jpg","pro-high-quality-canvas-jacket_2.jpg"],
    product_link: "https://capapiesports.com/product_details/pro-high-quality-canvas-jacket/B6KMC7LFIA",
  },
  {
    product_code: "1004",
    slug: "pro-high-quality-canvas-trouser",
    product_name: "PRO HIGH QUALITY CANVAS TROUSER",
    category: "Jackets & Trousers",
    short_description: "The Pro high-quality canvas jacket and trousers is a kit for the beginner serious target shooter.",
    long_description: "1. The Pro high-quality canvas jacket and trousers is a kit for the beginner serious target shooter.\n2. It has a perfectly customized anatomical cut, which provides increased stability, and fine quality double canvas gives the shooter the required edge.\n\nCanvas : Black | Red | Grey | Blue | Green | Sky Blue | Pink | Turquoise | Purple\nLeather & Piping Color : Black | Red | Green | White | Yellow |Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE",
    features: ["The Pro high-quality canvas jacket and trousers is a kit for the beginner serious target shooter.","It has a perfectly customized anatomical cut, which provides increased stability, and fine quality double canvas gives the shooter the required edge."],
    colors: [{"label":"Leather & Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE",
    image_filename: "pro-high-quality-canvas-trouser_1.jpg",
    images: ["pro-high-quality-canvas-trouser_1.jpg","pro-high-quality-canvas-trouser_2.jpg"],
    product_link: "https://capapiesports.com/product_details/pro-high-quality-canvas-trouser/1FWFLGNHVC",
  },
  {
    product_code: "1005",
    slug: "premium-jacket",
    product_name: "PREMIUM JACKET",
    category: "Jackets & Trousers",
    short_description: "Premium Jacket and Trousers have most of the features from our NSG CAPITEX® Jacket and Trousers such as CBC, and “Quick Draw Holster” Pocket.",
    long_description: "1. Premium Jacket and Trousers have most of the features from our NSG CAPITEX® Jacket and Trousers such as CBC, and “Quick Draw Holster” Pocket.\n\n1. Premium Jacket and Trousers are made of ISSF approved White Stiff PVC Material, along with a combination of genuine leather and stiff\ncanvas.\n2. White stiff PVC Material along with a combination of genuine leather and stiff canvas.\n3. PVC Material helps to maintain stiffness and thickness levels in all weather conditions.\nPremium Material: White\nCanvas : Black | Red |Grey | Blue | Green | Sky Bue | Pink | Turquoise | Purple\nLeather and Piping Color : Black | Red | Green | White | Yellow |Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    features: ["Premium Jacket and Trousers have most of the features from our NSG CAPITEX® Jacket and Trousers such as CBC, and “Quick Draw Holster” Pocket.","Premium Jacket and Trousers are made of ISSF approved White Stiff PVC Material, along with a combination of genuine leather and stiff","White stiff PVC Material along with a combination of genuine leather and stiff canvas.","PVC Material helps to maintain stiffness and thickness levels in all weather conditions."],
    colors: [{"label":"Leather and Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    image_filename: "premium-jacket_1.jpg",
    images: ["premium-jacket_1.jpg","premium-jacket_2.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-jacket/YODBW80RLF",
  },
  {
    product_code: "1006",
    slug: "premium-trouser",
    product_name: "PREMIUM TROUSER",
    category: "Jackets & Trousers",
    short_description: "Premium Jacket and Trousers have most of the features from our NSG CAPITEX® Jacket and Trousers such as CBC, and “Quick Draw Holster” Pocket.",
    long_description: "1. Premium Jacket and Trousers have most of the features from our NSG CAPITEX® Jacket and Trousers such as CBC, and “Quick Draw Holster” Pocket.\n\n1. Premium Jacket and Trouser are made of ISSF-approved White Stiff PVC Material, along with a combination of genuine leather and stiff canvas.\n2. White stiff PVC Material along with a combination of genuine leather and stiff canvas.\n3. PVC Material helps to maintain stiffness and thickness levels in all weather conditions.\nPremium Material: White\nCanvas : Black | Red |Grey | Blue | Green | Sky Bue | Pink | Turquoise | Purple\nLeather and Piping Color : Black | Red | Green | White | Yellow |Grey | Pink | Blue | Orange | Sky Blue | Purple",
    features: ["Premium Jacket and Trousers have most of the features from our NSG CAPITEX® Jacket and Trousers such as CBC, and “Quick Draw Holster” Pocket.","Premium Jacket and Trouser are made of ISSF-approved White Stiff PVC Material, along with a combination of genuine leather and stiff canvas.","White stiff PVC Material along with a combination of genuine leather and stiff canvas.","PVC Material helps to maintain stiffness and thickness levels in all weather conditions."],
    colors: [{"label":"Leather and Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "",
    image_filename: "premium-trouser_1.jpg",
    images: ["premium-trouser_1.jpg","premium-trouser_2.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-trouser/KGQHC38VXP",
  },
  {
    product_code: "1011",
    slug: "capi-square-jacket",
    product_name: "CAPI SQUARE JACKET",
    category: "Jackets & Trousers",
    short_description: "The Capi square CAPITEX® Jacket and Trouser has all the built qualities of its predecessor NSG CAPITEX®.",
    long_description: "1. The Capi square CAPITEX® Jacket and Trouser has all the built qualities of its predecessor NSG CAPITEX®.\n2. It has a regular V-neck design for those shooters who prefer it.\n\n1. This particular model from CAPAPIE comes with export-quality black anti-slip rubber.\nCAPITEX Material Color : White | Black | Red | Grey | Blue\nLeather and Piping Color : Black | Red | Green | White | Yellow | Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    features: ["The Capi square CAPITEX® Jacket and Trouser has all the built qualities of its predecessor NSG CAPITEX®.","It has a regular V-neck design for those shooters who prefer it.","This particular model from CAPAPIE comes with export-quality black anti-slip rubber."],
    colors: [{"label":"CAPITEX Material Color","values":["White","Black","Red","Grey","Blue"]},{"label":"Leather and Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    image_filename: "capi-square-jacket_1.jpg",
    images: ["capi-square-jacket_1.jpg","capi-square-jacket_2.jpg"],
    product_link: "https://capapiesports.com/product_details/capi-square-jacket/SGODJ43G1B",
  },
  {
    product_code: "1012",
    slug: "capi-square-trouser",
    product_name: "CAPI SQUARE TROUSER",
    category: "Jackets & Trousers",
    short_description: "The Capi square CAPITEX® Jacket and Trouser has all the built qualities of its predecessor NSG CAPITEX®.",
    long_description: "1. The Capi square CAPITEX® Jacket and Trouser has all the built qualities of its predecessor NSG CAPITEX®.\n2. It has a regular V-neck design for those shooters who prefer it.\n\n1.This particular model from CAPAPIE comes with export quality black anti-slip rubber.\nCAPITEX Material Color : White | Black | Red | Grey | Blue\nLeather and Piping Color : Black | Red | Green | White | Yellow | Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    features: ["The Capi square CAPITEX® Jacket and Trouser has all the built qualities of its predecessor NSG CAPITEX®.","It has a regular V-neck design for those shooters who prefer it.","This particular model from CAPAPIE comes with export quality black anti-slip rubber."],
    colors: [{"label":"CAPITEX Material Color","values":["White","Black","Red","Grey","Blue"]},{"label":"Leather and Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    image_filename: "capi-square-trouser_1.jpg",
    images: ["capi-square-trouser_1.jpg","capi-square-trouser_2.jpg"],
    product_link: "https://capapiesports.com/product_details/capi-square-trouser/CPZQCDRWRX",
  },
  {
    product_code: "1013",
    slug: "capi-pro-mix-jacket",
    product_name: "CAPI PRO MIX JACKET",
    category: "Jackets & Trousers",
    short_description: "The Capi Pro Mix Jacket and Trouser are made of a unique blend of ISSF-approved CAPITEX® Material and Pro Canvas Material.",
    long_description: "1. The Capi Pro Mix Jacket and Trouser are made of a unique blend of ISSF-approved CAPITEX® Material and Pro Canvas Material.\n2. This economical design is an ideal choice for those beginners who want the advantages of CAPITEX® Materials.\n\nCAPITEX Material Color: White\nCanvas : Black | Red | Grey | Blue| Green | Sky Blue | Pink | Turquoise | Purple\nLeather & Piping Color : Black | Red | Green | White | Yellow | Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    features: ["The Capi Pro Mix Jacket and Trouser are made of a unique blend of ISSF-approved CAPITEX® Material and Pro Canvas Material.","This economical design is an ideal choice for those beginners who want the advantages of CAPITEX® Materials."],
    colors: [{"label":"CAPITEX Material Color","values":["White"]},{"label":"Leather & Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    image_filename: "capi-pro-mix-jacket_1.jpg",
    images: ["capi-pro-mix-jacket_1.jpg","capi-pro-mix-jacket_2.jpg"],
    product_link: "https://capapiesports.com/product_details/capi-pro-mix-jacket/OTOTQRIJZN",
  },
  {
    product_code: "1014",
    slug: "capi-pro-mix-trouser",
    product_name: "CAPI PRO MIX TROUSER",
    category: "Jackets & Trousers",
    short_description: "The Capi Pro Mix Jacket and Trouser are made of a unique blend of ISSF-approved CAPITEX® Material and Pro Canvas Material.",
    long_description: "1. The Capi Pro Mix Jacket and Trouser are made of a unique blend of ISSF-approved CAPITEX® Material and Pro Canvas Material.\n2. This economical design is an ideal choice for those beginners who want the advantages of CAPITEX® Materials.\n\nCAPITEX Material Color: White\nCanvas : Black | Red | Grey | Blue| Green | Sky Blue | Pink | Turquoise | Purple\nLeather & Piping Color : Black | Red | Green | White | Yellow | Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    features: ["The Capi Pro Mix Jacket and Trouser are made of a unique blend of ISSF-approved CAPITEX® Material and Pro Canvas Material.","This economical design is an ideal choice for those beginners who want the advantages of CAPITEX® Materials."],
    colors: [{"label":"CAPITEX Material Color","values":["White"]},{"label":"Leather & Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    image_filename: "capi-pro-mix-trouser_1.jpg",
    images: ["capi-pro-mix-trouser_1.jpg","capi-pro-mix-trouser_2.jpg"],
    product_link: "https://capapiesports.com/product_details/capi-pro-mix-trouser/RZWIGBL3SR",
  },
  {
    product_code: "1015",
    slug: "nsg-capitex-topline-jacket",
    product_name: "NSG CAPITEX TOPLINE JACKET",
    category: "Jackets & Trousers",
    short_description: "Extended Top Grip Padding for better positioning of the butt plate in the prone and kneeling position",
    long_description: "1. Extended Top Grip Padding for better positioning of the butt plate in the prone and kneeling position\n2. Wide Top Grip Reinforcement for firm grip of butt plate in standing position\n3. Breathing Stabilizer in a standing position when the shooter is completely relaxed, his normal breathing causes in and out movement of the stomach. This affects the stability of the shooter\n4. Original Capapie Quick Draw Holster Pocket\n5. Anatomically cut leather button hole panel for perfect body fit at neck area\n6. Innovative Control Box Concept\n7. Soft full chrome Leather for Extra Comfort\n8. Soft, Thin, and Sweat free fabric inside the elbow area to bring the rifle-holding hand close to the body\n\n1. Multiple adjustable sling attachment\n2. Cutting edge fins for extra stability\n3. Dual reinforced horizontal stability band for extra support to lower back\n4. Anatomically designed vertical piping for extra support to your vertebra\n5. Soft and sturdy genuine leather gives perfect hold and comfortable feeling at the upper back area\n6. Double-holed adjustable non-stretchable belt on the upper back pulls and settles down the extra material in prone and kneeling positions.\n7. Top Grip Rubber with inner padding for firm grip in all shooting positions\n8. Black suede leather gives maximum grip to the rifle-holding hand\nCAPITEX Material Color: White | Black | Red | Grey | Blue\nLeather and Piping Color: Black | Red | Green | White | Yellow | Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    features: ["Extended Top Grip Padding for better positioning of the butt plate in the prone and kneeling position","Wide Top Grip Reinforcement for firm grip of butt plate in standing position","Breathing Stabilizer in a standing position when the shooter is completely relaxed, his normal breathing causes in and out movement of the stomach. This affects the stability of the shooter","Original Capapie Quick Draw Holster Pocket","Anatomically cut leather button hole panel for perfect body fit at neck area","Innovative Control Box Concept","Soft full chrome Leather for Extra Comfort","Soft, Thin, and Sweat free fabric inside the elbow area to bring the rifle-holding hand close to the body","Multiple adjustable sling attachment","Cutting edge fins for extra stability","Dual reinforced horizontal stability band for extra support to lower back","Anatomically designed vertical piping for extra support to your vertebra","Soft and sturdy genuine leather gives perfect hold and comfortable feeling at the upper back area","Double-holed adjustable non-stretchable belt on the upper back pulls and settles down the extra material in prone and kneeling positions.","Top Grip Rubber with inner padding for firm grip in all shooting positions","Black suede leather gives maximum grip to the rifle-holding hand"],
    colors: [{"label":"CAPITEX Material Color","values":["White","Black","Red","Grey","Blue"]},{"label":"Leather and Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSER FITTING PROGRAMME (JTFP).",
    image_filename: "nsg-capitex-topline-jacket_1.png",
    images: ["nsg-capitex-topline-jacket_1.png","nsg-capitex-topline-jacket_2.png","nsg-capitex-topline-jacket_3.png","nsg-capitex-topline-jacket_4.png"],
    product_link: "https://capapiesports.com/product_details/nsg-capitex-topline-jacket/ZADZLTOCK1",
  },
  {
    product_code: "1016",
    slug: "nsg-capitex-topline-trouser",
    product_name: "NSG CAPITEX TOPLINE TROUSER",
    category: "Jackets & Trousers",
    short_description: "Metal D-Loop Provided for use with suspenders",
    long_description: "1. Metal D-Loop Provided for use with suspenders\n2. Asymmetric placement of Top Grip reinforced pads\n3. Horizontal Velcro Strip provided for customized adjustments as per individual needs\n4. 2-inch vertical strap of velcro for adjustment at the hip as per individual needs\n5. Four-way expandable V-shaped Lycra for maximum comfort in kneeling positions\n\n1. Extended YKK zipper with lockable runners to settle down comfortably in kneeling positions. Also helps in easy wear/remove\n2. Two-way YKK zippers with lockable runners to prevent the zipper from opening during practice and competitions\n3. The rifle resting hand gets adequate support because of the extended Top Grip Pad\nCAPITEX Material Color: White | Black | Red | Grey | Blue\nLeather and Piping Color: Black | Red | Green | White | Yellow | Grey | Pink | Blue | Orange | Sky Blue | Purple\nAVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSERS FITTING PROGRAMME (JTFP).",
    features: ["Metal D-Loop Provided for use with suspenders","Asymmetric placement of Top Grip reinforced pads","Horizontal Velcro Strip provided for customized adjustments as per individual needs","2-inch vertical strap of velcro for adjustment at the hip as per individual needs","Four-way expandable V-shaped Lycra for maximum comfort in kneeling positions","Extended YKK zipper with lockable runners to settle down comfortably in kneeling positions. Also helps in easy wear/remove","Two-way YKK zippers with lockable runners to prevent the zipper from opening during practice and competitions","The rifle resting hand gets adequate support because of the extended Top Grip Pad"],
    colors: [{"label":"CAPITEX Material Color","values":["White","Black","Red","Grey","Blue"]},{"label":"Leather and Piping Color","values":["Black","Red","Green","White","Yellow","Grey","Pink","Blue","Orange","Sky Blue","Purple"]}],
    sizing: "AVAILABLE IN STANDARD SIZES, MADE TO MEASURE, AND JACKET TROUSERS FITTING PROGRAMME (JTFP).",
    image_filename: "nsg-capitex-topline-trouser_1.jpg",
    images: ["nsg-capitex-topline-trouser_1.jpg","nsg-capitex-topline-trouser_2.jpg"],
    product_link: "https://capapiesports.com/product_details/nsg-capitex-topline-trouser/USMBZHO4JS",
  },
  {
    product_code: "1092",
    slug: "semi-pro-v2-jacket",
    product_name: "SEMI-PRO V2 JACKET",
    category: "Jackets & Trousers",
    short_description: "Semi Pro V-2 Jacket",
    long_description: "Semi Pro V-2 Jacket\n\nThe Stiff Canvas Jacket and Trouser is the basic kit for junior and hobby target shooters. This Material provides the required stability for new shooters and gives them a feel of their gear.\nCanvas: Sky Blue\nLeather Color: Black\nPiping and Name to appear: Blue\nAvailable in standard sizes",
    features: [],
    colors: [{"label":"Leather Color","values":["Black"]}],
    sizing: "Available in standard sizes",
    image_filename: "semi-pro-v2-jacket_1.png",
    images: ["semi-pro-v2-jacket_1.png","semi-pro-v2-jacket_2.png"],
    product_link: "https://capapiesports.com/product_details/semi-pro-v2-jacket/OMNOZCXTUO",
  },
  {
    product_code: "1093",
    slug: "semi-pro-v2-trouser",
    product_name: "SEMI-PRO V2 TROUSER",
    category: "Jackets & Trousers",
    short_description: "Semi Pro V2 Trouser",
    long_description: "Semi Pro V2 Trouser\n\nThe Stiff Canvas Jacket and Trouser is the basic kit for junior and hobby target shooters. This Material provides the required stability for new shooters and gives them a feel of their gear.\nCanvas: Sky Blue\nLeather Color: Black\nPiping and Name to appear: Blue\nAvailable in standard sizes",
    features: [],
    colors: [{"label":"Leather Color","values":["Black"]}],
    sizing: "Available in standard sizes",
    image_filename: "semi-pro-v2-trouser_1.png",
    images: ["semi-pro-v2-trouser_1.png","semi-pro-v2-trouser_2.png"],
    product_link: "https://capapiesports.com/product_details/semi-pro-v2-trouser/UZODZIYZPQ",
  },
  {
    product_code: "1017",
    slug: "premium-rifle-shooting-shoes",
    product_name: "PREMIUM RIFLE SHOOTING SHOES",
    category: "Shoes",
    short_description: "Sole is consolidated with three layers.",
    long_description: "Our Premium rifle shooting shoes are a perfect masterpiece of Indian handicrafts. With an extra keen eye, we have developed these shoes to meet the requirements of all three shooting positions. The finest quality breathable leather is used in this product.\n\n1. Sole is consolidated with three layers.\n2. Rigid layer for better support.\n3. Soft middle layer for maximum comfort.\n4. Anti-slip layer with hollow area for a firm grip.\n5. Two padded soft tongues designed to enhance comfort in front and back.\n6. Removable adjustable Velcro strap for better fit and style.",
    features: ["Sole is consolidated with three layers.","Rigid layer for better support.","Soft middle layer for maximum comfort.","Anti-slip layer with hollow area for a firm grip.","Two padded soft tongues designed to enhance comfort in front and back.","Removable adjustable Velcro strap for better fit and style."],
    colors: [],
    sizing: "",
    image_filename: "premium-rifle-shooting-shoes_1.jpg",
    images: ["premium-rifle-shooting-shoes_1.jpg","premium-rifle-shooting-shoes_2.jpg","premium-rifle-shooting-shoes_3.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-rifle-shooting-shoes/MZE6OL5D5T",
  },
  {
    product_code: "1018",
    slug: "premium-pistol-shooting-shoes",
    product_name: "PREMIUM PISTOL SHOOTING SHOES",
    category: "Shoes",
    short_description: "With all the build qualities of the rifle shoes, these pistol shoes shaped with a boot cut pattern, are lightweight, and can withstand a great amount of bend as per ISSF rules. The ankle edge is reinforced with extra padding for stability.",
    long_description: "With all the build qualities of the rifle shoes, these pistol shoes shaped with a boot cut pattern, are lightweight, and can withstand a great amount of bend as per ISSF rules. The ankle edge is reinforced with extra padding for stability.",
    features: [],
    colors: [],
    sizing: "",
    image_filename: "premium-pistol-shooting-shoes_1.jpg",
    images: ["premium-pistol-shooting-shoes_1.jpg","premium-pistol-shooting-shoes_2.jpg","premium-pistol-shooting-shoes_3.jpg"],
    product_link: "https://capapiesports.com/product_details/premium-pistol-shooting-shoes/QZLCEAJRYP",
  }
];

function toDisplayProduct(product: CapapieProduct): DisplayProduct {
  const images = (product.images && product.images.length > 0
    ? product.images
    : [product.image_filename]
  ).map((f) => (f.startsWith('/') ? f : `/images/products/${f}`));

  return {
    product_code: product.product_code,
    slug: product.slug,
    name: product.product_name,
    category: product.category,
    short_description: product.short_description,
    long_description: product.long_description || '',
    features: product.features || [],
    colors: product.colors || [],
    sizing: product.sizing || '',
    image_path: images[0] || '/images/products/placeholder.png',
    images,
    product_link: product.product_link,
  };
}

export function getAllCapapieProducts(): DisplayProduct[] {
  return capapieProductsData.map(toDisplayProduct);
}

export function getCapapieProductByCode(product_code: string): DisplayProduct | undefined {
  const product = capapieProductsData.find((p) => p.product_code === product_code);
  return product ? toDisplayProduct(product) : undefined;
}

export function getCapapieProductBySlug(slug: string): DisplayProduct | undefined {
  const product = capapieProductsData.find((p) => p.slug === slug);
  return product ? toDisplayProduct(product) : undefined;
}

export function getCapapieProductsByCategory(category: string): DisplayProduct[] {
  return capapieProductsData
    .filter((p) => p.category.toLowerCase() === category.toLowerCase())
    .map(toDisplayProduct);
}

export function getCapapieCategories(): string[] {
  const categories = new Set(capapieProductsData.map((p) => p.category));
  return Array.from(categories).sort();
}

export function getFeaturedCapapieProducts(): DisplayProduct[] {
  const featuredCodes = ['1015', '1005', '1017', '1079'];
  const all = getAllCapapieProducts();
  const featured = all.filter((p) => featuredCodes.includes(p.product_code));
  // Fall back to first 4 products if the curated codes are missing.
  return (featured.length >= 4 ? featured : all).slice(0, 4);
}
