import { DisplayProduct } from '@/types/product-data';
import {
  getAllCapapieProducts,
  getCapapieCategories,
  getCapapieProductsByCategory,
} from './capapie-products';
import { getShotgunProducts } from './shotgun-products';

/**
 * Unified catalogue across both shooting disciplines.
 *
 * lib/capapie-products.ts is regenerated by `pnpm scrape-products`, so the
 * merge/normalisation logic lives here instead of in that generated file.
 * Precision products are normalised to discipline 'precision'; the Trap &
 * Skeet range comes from the hand-authored lib/shotgun-products.ts.
 */

function normalisePrecision(product: DisplayProduct): DisplayProduct {
  return {
    ...product,
    discipline: 'precision',
    brand: product.brand ?? 'Capapie',
    made_to_measure: product.made_to_measure ?? false,
    image_alt: product.image_alt ?? product.name,
  };
}

export function getPrecisionProducts(): DisplayProduct[] {
  return getAllCapapieProducts().map(normalisePrecision);
}

/** Category names for the precision (ISSF) range only. */
export function getPrecisionCategories(): string[] {
  return getCapapieCategories();
}

export function getPrecisionProductsByCategory(category: string): DisplayProduct[] {
  return getCapapieProductsByCategory(category).map(normalisePrecision);
}

/** Every product on the site, both disciplines. */
export function getAllProducts(): DisplayProduct[] {
  return [...getPrecisionProducts(), ...getShotgunProducts()];
}

/** Resolves a product by its (globally unique) slug across both disciplines. */
export function getProductBySlug(slug: string): DisplayProduct | undefined {
  return getAllProducts().find((p) => p.slug === slug);
}

/**
 * Related products for a given product: same category first, then same
 * discipline, excluding the product itself.
 */
export function getRelatedProducts(product: DisplayProduct, count = 4): DisplayProduct[] {
  const pool = getAllProducts().filter(
    (p) => p.slug !== product.slug && p.discipline === product.discipline
  );
  const sameCategory = pool.filter((p) => p.category === product.category);
  const rest = pool.filter((p) => p.category !== product.category);
  return [...sameCategory, ...rest].slice(0, count);
}
